# Generated by Django 3.0.7 on 2020-07-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('score', models.FloatField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segint_api.Feedback')),
            ],
        ),
    ]
