# Generated by Django 3.0.7 on 2020-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0005_mlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb', models.FileField(upload_to='modelfamily/')),
            ],
        ),
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
