# Generated by Django 3.0.7 on 2020-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0007_segmentationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationtask',
            name='model_id',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
