# Generated by Django 3.0.7 on 2020-07-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0009_segmentationtask_model_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationtask',
            name='time_field',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
