# Generated by Django 3.0.7 on 2020-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0010_auto_20200714_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationtask',
            name='segmentation_id',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
