# Generated by Django 3.0.7 on 2020-07-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0011_segmentationtask_segmentation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationtask',
            name='segmentation_id',
            field=models.UUIDField(null=True),
        ),
    ]
