# Generated by Django 3.0.7 on 2020-07-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0013_auto_20200715_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SegmentationTask',
            new_name='SegmentationJob',
        ),
    ]
