# Generated by Django 3.0.7 on 2020-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0014_auto_20200715_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
