# Generated by Django 3.0.7 on 2020-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0015_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_software_version', models.CharField(max_length=60)),
                ('upload_time_ms', models.IntegerField()),
                ('segmentation_wait_ms', models.IntegerField()),
                ('segmentation_down_ms', models.IntegerField()),
                ('segmentation_retries', models.IntegerField()),
                ('segmentation_model_id', models.CharField(max_length=60)),
                ('segmentation_id', models.CharField(max_length=60)),
                ('client_error', models.IntegerField()),
                ('client_error_info', models.TextField()),
            ],
        ),
    ]
