# Generated by Django 3.0.7 on 2020-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0019_auto_20200727_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartExamined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.IntegerField(blank=True, choices=[(0, 'Abdomen'), (1, 'Abdomenpelvis'), (2, 'Adrenal'), (3, 'Ankle'), (4, 'Aorta'), (5, 'Axilla'), (6, 'Back'), (7, 'Bladder'), (8, 'Brain'), (9, 'Breast'), (10, 'Bronchus'), (11, 'Buttock'), (12, 'Calcaneus'), (13, 'Calf'), (14, 'Carotid'), (15, 'Cerebellum'), (16, 'Cspine'), (17, 'Ctspine'), (18, 'Cervix'), (19, 'Cheek'), (20, 'Chest'), (21, 'Chestabdomen'), (22, 'Chestabdomenpelvis'), (23, 'Circleofwillis'), (24, 'Clavicle'), (25, 'Coccyx'), (26, 'Colon'), (27, 'Cornea'), (28, 'Coronaryartery'), (29, 'Duodenum'), (30, 'Ear'), (31, 'Elbow'), (32, 'Wholebody'), (33, 'Esophagus'), (34, 'Extremity'), (35, 'Eye'), (36, 'Eyelid'), (37, 'Face'), (38, 'Femur'), (39, 'Finger'), (40, 'Foot'), (41, 'Gallbladder'), (42, 'Hand'), (43, 'Head'), (44, 'Headneck'), (45, 'Heart'), (46, 'Hip'), (47, 'Humerus'), (48, 'Ileum'), (49, 'Ilium'), (50, 'Iac'), (51, 'Jaw'), (52, 'Jejunum'), (53, 'Kidney'), (54, 'Knee'), (55, 'Larynx'), (56, 'Liver'), (57, 'Leg'), (58, 'Lspine'), (59, 'Lsspine'), (60, 'Lung'), (61, 'Maxilla'), (62, 'Mediastinum'), (63, 'Mouth'), (64, 'Neck'), (65, 'Neckchest'), (66, 'Neckchestabdomen'), (67, 'Neckchestabdomenpelvis'), (68, 'Nose'), (69, 'Orbit'), (70, 'Ovary'), (71, 'Pancreas'), (72, 'Parotid'), (73, 'Patella'), (74, 'Pelvis'), (75, 'Penis'), (76, 'Pharynx'), (77, 'Prostate'), (78, 'Rectum'), (79, 'Rib'), (80, 'Sspine'), (81, 'Scalp'), (82, 'Scapula'), (83, 'Sclera'), (84, 'Scrotum'), (85, 'Shoulder'), (86, 'Skull'), (87, 'Spine'), (88, 'Spleen'), (89, 'Sternum'), (90, 'Stomach'), (91, 'Summandibular'), (92, 'Tmjoint'), (93, 'Testis'), (94, 'Thigh'), (95, 'Tspine'), (96, 'Tlspine'), (97, 'Thumb'), (98, 'Thymus'), (99, 'Thyroid'), (100, 'Toe'), (101, 'Tongue'), (102, 'Trachea'), (103, 'Arm'), (104, 'Ureter'), (105, 'Urethra'), (106, 'Uterus'), (107, 'Vagina'), (108, 'Vulva'), (109, 'Wrist'), (110, 'Zygoma')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='anatomical_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='clinical_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Any')], null=True),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='language_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='modalities',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelfamily',
            name='primary_structure',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
