# Generated by Django 3.0.7 on 2020-07-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0020_auto_20200727_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypartexamined',
            name='model_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='segint_api.ModelFamily'),
        ),
    ]
