# Generated by Django 3.0.7 on 2020-07-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0022_acceptedmodality_modelchanneldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_max_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_max_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_max_z',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_min_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_min_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='dimensions_min_z',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='is_axial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='model_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='segint_api.ModelFamily'),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='req_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_max_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_max_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_max_z',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_min_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_min_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelchanneldescription',
            name='spacing_min_z',
            field=models.IntegerField(null=True),
        ),
    ]
