# Generated by Django 3.0.7 on 2020-07-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0024_auto_20200727_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='segint_api.ModelFamily'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_version_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
