# Generated by Django 3.0.7 on 2020-07-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0025_auto_20200727_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='credits_req',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='language_code',
            field=models.CharField(default='en', max_length=200),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='major_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='minor_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_version_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color_r', models.IntegerField(default=0)),
                ('color_g', models.IntegerField(default=0)),
                ('color_b', models.IntegerField(default=0)),
                ('structure_type', models.IntegerField(blank=True, choices=[(0, 'External'), (1, 'Organ'), (2, 'Unknown')], null=True)),
                ('FMA_code', models.IntegerField(default=0)),
                ('input_channel_id', models.CharField(max_length=200)),
                ('structure_id', models.CharField(max_length=200)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='segint_api.ModelFamily')),
            ],
        ),
    ]
