# Generated by Django 3.0.7 on 2020-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0026_auto_20200727_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchanneldescription',
            name='accepted_modalities_pb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='AcceptedModality',
        ),
    ]
