# Generated by Django 3.0.7 on 2020-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0029_auto_20200728_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfamily',
            name='pb',
            field=models.FileField(blank=True, null=True, upload_to='modelfamily/'),
        ),
    ]
