# Generated by Django 3.0.7 on 2020-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0030_auto_20200728_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
