# Generated by Django 3.0.7 on 2020-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0031_auto_20200728_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_module',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
