# Generated by Django 3.0.7 on 2020-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0032_modelversion_model_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
