# Generated by Django 3.0.7 on 2020-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0033_modelversion_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='model_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Phantom'), (1, 'Pytorch'), (2, 'Tensorflow')], null=True),
        ),
    ]
