# Generated by Django 3.0.7 on 2020-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segint_api', '0034_auto_20200807_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationtelemetry',
            name='client_software_version',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='segmentationtelemetry',
            name='segmentation_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='segmentationtelemetry',
            name='segmentation_model_id',
            field=models.CharField(max_length=200),
        ),
    ]
