# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Primitives3D.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Primitives3D.proto',
  package='Radiomics',
  syntax='proto3',
  serialized_options=b'\252\002+Microsoft.Radiomics.Segmentation.API.Proto3',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12Primitives3D.proto\x12\tRadiomics\"+\n\x08Vector3D\x12\t\n\x01X\x18\x01 \x01(\x01\x12\t\n\x01Y\x18\x02 \x01(\x01\x12\t\n\x01Z\x18\x03 \x01(\x01\"\xe8\x01\n\x0bTransform3D\x12+\n\x0eXAxisDirection\x18\x01 \x01(\x0b\x32\x13.Radiomics.Vector3D\x12+\n\x0eYAxisDirection\x18\x02 \x01(\x0b\x32\x13.Radiomics.Vector3D\x12+\n\x0eZAxisDirection\x18\x03 \x01(\x0b\x32\x13.Radiomics.Vector3D\x12-\n\x10VoxelScalingInMM\x18\x04 \x01(\x0b\x32\x13.Radiomics.Vector3D\x12#\n\x06Origin\x18\x05 \x01(\x0b\x32\x13.Radiomics.Vector3D\"l\n\x12\x43\x61libratedVolume3D\x12-\n\rDataTransform\x18\x04 \x01(\x0b\x32\x16.Radiomics.Transform3D\x12\'\n\x06Volume\x18\x02 \x01(\x0b\x32\x17.Radiomics.VolumeData3D\"\x9a\x02\n\x0cVolumeData3D\x12\r\n\x05Width\x18\x01 \x01(\r\x12\x0e\n\x06Height\x18\x02 \x01(\r\x12\r\n\x05\x44\x65pth\x18\x03 \x01(\r\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\x0c\x12\x33\n\x08\x44\x61taType\x18\x05 \x01(\x0e\x32!.Radiomics.VolumeData3D.DataTypes\x12\x45\n\x11\x43ompressionMethod\x18\x06 \x01(\x0e\x32*.Radiomics.VolumeData3D.CompressionMethods\"2\n\tDataTypes\x12\x1b\n\x17LittleEndianSignedInt16\x10\x00\x12\x08\n\x04\x42yte\x10\x01\"\x1e\n\x12\x43ompressionMethods\x12\x08\n\x04Gzip\x10\x00\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05Value\x18\x01 \x01(\x01\x42.\xaa\x02+Microsoft.Radiomics.Segmentation.API.Proto3b\x06proto3'
)



_VOLUMEDATA3D_DATATYPES = _descriptor.EnumDescriptor(
  name='DataTypes',
  full_name='Radiomics.VolumeData3D.DataTypes',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LittleEndianSignedInt16', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Byte', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=624,
  serialized_end=674,
)
_sym_db.RegisterEnumDescriptor(_VOLUMEDATA3D_DATATYPES)

_VOLUMEDATA3D_COMPRESSIONMETHODS = _descriptor.EnumDescriptor(
  name='CompressionMethods',
  full_name='Radiomics.VolumeData3D.CompressionMethods',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Gzip', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=676,
  serialized_end=706,
)
_sym_db.RegisterEnumDescriptor(_VOLUMEDATA3D_COMPRESSIONMETHODS)


_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='Radiomics.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Radiomics.Vector3D.X', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Radiomics.Vector3D.Y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Z', full_name='Radiomics.Vector3D.Z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=76,
)


_TRANSFORM3D = _descriptor.Descriptor(
  name='Transform3D',
  full_name='Radiomics.Transform3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='XAxisDirection', full_name='Radiomics.Transform3D.XAxisDirection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='YAxisDirection', full_name='Radiomics.Transform3D.YAxisDirection', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ZAxisDirection', full_name='Radiomics.Transform3D.ZAxisDirection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VoxelScalingInMM', full_name='Radiomics.Transform3D.VoxelScalingInMM', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Origin', full_name='Radiomics.Transform3D.Origin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=311,
)


_CALIBRATEDVOLUME3D = _descriptor.Descriptor(
  name='CalibratedVolume3D',
  full_name='Radiomics.CalibratedVolume3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='DataTransform', full_name='Radiomics.CalibratedVolume3D.DataTransform', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Volume', full_name='Radiomics.CalibratedVolume3D.Volume', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=421,
)


_VOLUMEDATA3D = _descriptor.Descriptor(
  name='VolumeData3D',
  full_name='Radiomics.VolumeData3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Width', full_name='Radiomics.VolumeData3D.Width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Height', full_name='Radiomics.VolumeData3D.Height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Depth', full_name='Radiomics.VolumeData3D.Depth', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='Radiomics.VolumeData3D.Data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DataType', full_name='Radiomics.VolumeData3D.DataType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CompressionMethod', full_name='Radiomics.VolumeData3D.CompressionMethod', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VOLUMEDATA3D_DATATYPES,
    _VOLUMEDATA3D_COMPRESSIONMETHODS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=706,
)


_DOUBLEVALUE = _descriptor.Descriptor(
  name='DoubleValue',
  full_name='Radiomics.DoubleValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='Radiomics.DoubleValue.Value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=736,
)

_TRANSFORM3D.fields_by_name['XAxisDirection'].message_type = _VECTOR3D
_TRANSFORM3D.fields_by_name['YAxisDirection'].message_type = _VECTOR3D
_TRANSFORM3D.fields_by_name['ZAxisDirection'].message_type = _VECTOR3D
_TRANSFORM3D.fields_by_name['VoxelScalingInMM'].message_type = _VECTOR3D
_TRANSFORM3D.fields_by_name['Origin'].message_type = _VECTOR3D
_CALIBRATEDVOLUME3D.fields_by_name['DataTransform'].message_type = _TRANSFORM3D
_CALIBRATEDVOLUME3D.fields_by_name['Volume'].message_type = _VOLUMEDATA3D
_VOLUMEDATA3D.fields_by_name['DataType'].enum_type = _VOLUMEDATA3D_DATATYPES
_VOLUMEDATA3D.fields_by_name['CompressionMethod'].enum_type = _VOLUMEDATA3D_COMPRESSIONMETHODS
_VOLUMEDATA3D_DATATYPES.containing_type = _VOLUMEDATA3D
_VOLUMEDATA3D_COMPRESSIONMETHODS.containing_type = _VOLUMEDATA3D
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Transform3D'] = _TRANSFORM3D
DESCRIPTOR.message_types_by_name['CalibratedVolume3D'] = _CALIBRATEDVOLUME3D
DESCRIPTOR.message_types_by_name['VolumeData3D'] = _VOLUMEDATA3D
DESCRIPTOR.message_types_by_name['DoubleValue'] = _DOUBLEVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3D,
  '__module__' : 'Primitives3D_pb2'
  # @@protoc_insertion_point(class_scope:Radiomics.Vector3D)
  })
_sym_db.RegisterMessage(Vector3D)

Transform3D = _reflection.GeneratedProtocolMessageType('Transform3D', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORM3D,
  '__module__' : 'Primitives3D_pb2'
  # @@protoc_insertion_point(class_scope:Radiomics.Transform3D)
  })
_sym_db.RegisterMessage(Transform3D)

CalibratedVolume3D = _reflection.GeneratedProtocolMessageType('CalibratedVolume3D', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEDVOLUME3D,
  '__module__' : 'Primitives3D_pb2'
  # @@protoc_insertion_point(class_scope:Radiomics.CalibratedVolume3D)
  })
_sym_db.RegisterMessage(CalibratedVolume3D)

VolumeData3D = _reflection.GeneratedProtocolMessageType('VolumeData3D', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMEDATA3D,
  '__module__' : 'Primitives3D_pb2'
  # @@protoc_insertion_point(class_scope:Radiomics.VolumeData3D)
  })
_sym_db.RegisterMessage(VolumeData3D)

DoubleValue = _reflection.GeneratedProtocolMessageType('DoubleValue', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEVALUE,
  '__module__' : 'Primitives3D_pb2'
  # @@protoc_insertion_point(class_scope:Radiomics.DoubleValue)
  })
_sym_db.RegisterMessage(DoubleValue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
